version: "3.3"

services: 
  frontend: 
    container_name: #PROJECT_NAME#.frontend 
    env_file:
      - .env 
    build: 
      context: ./frontend 
      dockerfile: Dockerfile 
    user: root 
    ports: 
      - "${FRONTEND_PORT}:5173" 
    privileged: true 
    volumes: 
      - ./frontend:/home/#PROJECT_NAME#.frontend 
    networks: 
      main:
        ipv4_address: #IP_PREFIX#.101


  backend: 
    container_name: #PROJECT_NAME#.backend 
    env_file: 
      - .env 
    build: 
      context: ./backend 
      dockerfile: Dockerfile
    tty: true
    user: root 
    ports: 
      - "${BACKEND_PORT}:3333"
    privileged: true 
    volumes: 
      - ./backend:/home/#PROJECT_NAME#.backend 
    networks: 
      main:
        ipv4_address: #IP_PREFIX#.102

  cache: 
    container_name: #PROJECT_NAME#.redis
    env_file: 
      - .env 
    image: redis:7.2.4-alpine 
    user: root
    restart: always
    ports: 
      - "${REDIS_PORT}:6379"
    privileged: true
    command: 
      redis-server --requirepass ${REDIS_PASSWORD} 
    volumes: 
      - redis:/data
      - ./backend/config/redis.conf:/usr/local/redis/redis.conf
    networks: 
      main:
        ipv4_address: #IP_PREFIX#.103

  database: 
    container_name: #PROJECT_NAME#.database
    env_file: 
      - .env 
    image: mariadb:11.2.4-jammy
    user: root
    environment:
      - MARIADB_ROOT_USERNAME=${MARIADB_USERNAME}
      - MARIADB_ROOT_PASSWORD=${MARIADB_PASSWORD}
    ports:
      - "${MARIADB_PORT}:3306"
    volumes: 
      - database:/data/db
    networks: 
      main:
        ipv4_address: #IP_PREFIX#.104
    
  phpmyadmin: 
    container_name: #PROJECT_NAME#.phpmyadmin
    env_file: 
      - .env 
    image: phpmyadmin:5.2.1
    restart: always
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=172.28.2.5
      - PMA_PORT=30003
    networks:
      main:
        ipv4_address: #IP_PREFIX#.105
      

volumes: 
  redis:
    driver: local
  database: 
    driver: local

networks: 
  main: 
    ipam:
        driver: default
        config:
          - subnet: #IP_PREFIX#.0/16